# Configuration file for LocalEnv tool
python:
  image: "python:3.12"
  default_container_name: "pyEnv"
  base_command: "python"

powershell:
  image: "mcr.microsoft.com/powershell:latest"
  default_container_name: "psEnv"
  base_command: ""

groovy:
  image: "groovy:latest"
  default_container_name: "groovyEnv"
  base_command: "groovy"

javascript:
  image: "node:latest"
  default_container_name: "javascriptEnv"
  base_command: "node"
